/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devopsfordefense.cmdemo;

import java.io.FileInputStream;
import java.util.List;
import java.util.Properties;

public class App {

    private static final String AGG_STRATEGY_SUM = "SUM";
    private static final String AGG_STRATEGY_MEAN = "MEAN";

    private static final String AGG_STRATEGY_TOGGLE = "AGG_STRATEGY";
    
    public static void main(String[] args) throws Exception {

        Properties config = new Properties();
        config.load(new FileInputStream(args[0]));

        NumberGenerator numGen = new NumberGenerator();
        List<Double> nums = numGen.generate();
        System.out.println("Generated " + nums.size() + " numbers.");

        NumberAggregator numAgg = null;
        
        if(AGG_STRATEGY_SUM.equals(config.getProperty(AGG_STRATEGY_TOGGLE))) {
            numAgg = new NumberAggregatorSum();
        } else if(AGG_STRATEGY_MEAN.equals(config.getProperty(AGG_STRATEGY_TOGGLE))) {
            numAgg = new NumberAggregatorMean();
        }
        double value = numAgg.aggregate(nums);
        System.out.println("Aggregated value is " + value);
    }
}
