/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devopsfordefense.cmdemo;

import java.util.List;

public class App {
    
    public static void main(String[] args) {

        NumberGenerator numGen = new NumberGenerator();
        List<Double> nums = numGen.generate();
        System.out.println("Generated " + nums.size() + " numbers.");
    }
}
